// Copyright (c) Alexis Chân Gridel. All Rights Reserved.
// Licensed under the GNU General Public License v3.0.
// See the LICENSE file in the project root for more information.

namespace PlanetSalvator.Web.Server.Handlers;

using MediatR;
using PlanetSalvator.Web.Server.Queries;
using PlanetSalvator.Web.Shared.Dtos;

public record GetPracticalTipsHandler
    : IRequestHandler<GetPracticalTipsQuery, IEnumerable<PracticalTip>>
{
    private static readonly IReadOnlySet<PracticalTip> PracticalTips = new HashSet<PracticalTip>
    {
        new(
            "Comment les cartons sont recyclés ?",
            "Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine. Les cartons sont recyclés dans leur état d'origine "),
        new(
            "DIY: Créer un composteur",
            "Pour créer un composteur, prenez un sac poubelle, un carton, un bac de compost, un bac de poussière, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets, un bac de déchets"),
        new(
            "Comment fonctionne les bennes à ordure ?",
            "Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux. Les bennes à ordure sont des bacs de déchets qui sont utilisés pour stocker les déchets dangereux."),
        new(
            "10 choses à faire pour préserver notre belle planète",
            "1. Ne pas faire de déchets dangereux dans les bacs à ordure.\n2. Ne pas faire de déchets dangereux dans les bacs à ordure.\n3. Ne pas faire de déchets dangereux dans les bacs à ordure.\n4. Ne pas faire de déchets dangereux dans les bacs à ordure.\n5. Ne pas faire de déchets dangereux dans les bacs à ordure.\n6. Ne pas faire de déchets dangereux dans les bacs à ordure.\n7. Ne pas faire de déchets dangereux dans les bacs à ordure.\n8. Ne pas faire de déchets dangereux dans les bacs à ordure.\n9. Ne pas faire de déchets dangereux dans les bacs à ordure.\n10. Ne pas faire de déchets dangereux dans les bacs à ordure."),
        new(
            "Qui est Greta Thunberg ?",
            "Greta Thunberg est une actrice et écrivaine américaine née le 7 avril 1937 à New York. Elle est la fille de l'actrice et de l'écrivain Greta Thunberg. Elle a été nomée comme une des personnages les plus importantes de l'histoire de l'amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première femme à avoir été nomée comme une personnage de l'histoire de l'Amérique du Nord. Elle a été la première fem"),
        new(
            "Fermez vos robinets peut sauver la planète ?",
            "Oui, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\n"),
        new(
            "Vais-je gagner la bourse Coddity ?",
            "Oui, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bonne idée, mais il faut les fermer avec des clés.\nC'est une bon"),
    };


    /// <inheritdoc />
    public Task<IEnumerable<PracticalTip>> Handle(GetPracticalTipsQuery request, CancellationToken cancellationToken)
    {
        // It's obvious that DailyTasks won't never be null, but let's simulate that the DailyTasks data are from an external source.
        return Task.FromResult(PracticalTips.Take(request.Count)
                               ?? Enumerable.Empty<PracticalTip>());
    }
}